config/routes.rb
Timekeepr::Application.routes.draw do
  devise_for :users
  root 'welcome#index'
  resources :accounts
end

app/models/account.rb
class Account < ActiveRecord::Base
  RESTRICTED_SUBDOMAINS = %w(www) #%w allows us to specifiy an array of strings without using delimiters
  belongs_to :owner, class_name: 'User'

  validates :owner, presence: true
  validates :subdomain, presence: true,
                        uniqueness: { case_sensitive: false },
                        format: { with: /\A[\w\-]+\Z/i, message: 'contains invalid characters' }, #regex to allow us to get rid of characters we don't want
                        #\A and \Z denotes beginning and end of string
                        #\w any character a-z & any number and ( _ )
                        #\- to allow -
                        #+ will allow any number of \w \- to appear
                        #make the whole thing case insensitive
                          exclusion: { in: RESTRICTED_SUBDOMAINS, message: 'restricted' } #validate the subdomain chosen is not in a list of restricted subdomains

  accepts_nested_attributes_for :owner


  before_validation :downcase_subdomain

  private

  def downcase_subdomain
    self.subdomain = subdomain.try(:downcase)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :recoverable, :rememberable, :validatable

  validates :name, presence: true
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  def new
    @account = Account.new
    @account.build_owner
  end

  def create
    @account = Account.new(account_params)
    if @account.save
      redirect_to root_path, notice: 'Signed up successfully'
    else
      render action: 'new'
    end
  end

  private
  def account_params
    params.require(:account).permit(:subdomain, owner_attributes: [:name, :email, :password, :pasword_confirmation])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/form_helper.rb
module FormHelper
  def errors_for(form, field)
    content_tag(:p, form.object.errors[field].try(:first), class: 'help-block')
  end

    #takes the form that we're working with, the particular fields, and a block
  def form_group_for(form, field, opts={}, &block)
    label = opts.fetch(:label) { true }
    #checks if the form field has errors
    has_errors = form.object.errors[field].present?

    #then it's going to create a div with the styles that bootstrap 3 expects
    content_tag :div, class: "form-group #{'has-error' if has_errors}" do
      #then it's going to create a lable for our field
      concat form.label(field, class: 'control-label') if label
      #output whatever is in the block, in this case it's going to be an input
      concat capture(&block)
      #then it's going to output any errors associated with that field
      concat errors_for(form, field)
    end
  end 
end

app/helpers/layout_helper.rb
 module LayoutHelper
  def flash_messages(opts={})
    @layout_flash = opts.fetch(:layout_flash) { true }

    capture do
      flash.each do |name, msg|
        concat content_tag(:div, msg, id: "flash_#{name}")
      end
    end
  end

  def show_layout_flash?
    @layout_flash.nil? ? true : @layout_flash
  end

end

app/views/accounts/new.html.erb
<div class="col-md-6 col-md-offset-3 panel panel-default">
  <div class="panel-body">
    <h2>Create an account</h2>

    <%= form_for @account do |f| %>
      <%= f.fields_for :owner do |o| %>
        <%= form_group_for o, :name do %>
          <%= o.text_field :name, class: 'form-control' %>
        <% end %>
        <%= form_group_for o, :email do %>
          <%= o.text_field :email, class: 'form-control' %>
        <% end %>
        <%= form_group_for o, :password do %>
          <%= o.password_field :password, class: 'form-control' %>
        <% end %>
        <%= form_group_for o, :password_confirmation do %>
          <%= o.password_field :password_confirmation, class: 'form-control' %>
        <% end %>
      <% end %>

      <%= form_group_for f, :subdomain do %>
        <div class="input-group">
          <%= f.text_field :subdomain, class: 'form-control' %>
          <span class="input-group-addon">.timekeepr.dev</span>
        </div>
      <% end %>

      <%= f.submit class: 'btn btn-primary'%>

    <% end %>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timekeepr</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<header class="container">
  <nav class="navbar navbar-default">
    <div class="navbar-header">
      <%= link_to 'Time Keepr', root_path, class: 'navbar-brand' %>
    </div>

    <div class="pull-right right-buttons">
      <% if user_signed_in? %>
        <%= link_to 'Sign out', destroy_user_session_path, method: 'delete', class: 'btn btn-default navbar-btn' %>
      <% end %>
    </div>
  </nav>
</header>

<body>
  <div class="container">

    <%= flash_messages if show_layout_flash? %>

    <div class="row">
      <%= yield %>
    </div>

  </div>
</body>
</html>

app/views/welcome/index.html.erb
<div class="col-md-12">
  <div class="jumbotron">
    <h1>Time Tracker</h1>
    <p>
      Track your time with the most awesome time tracking app ever.
    </p>
    <p><%= link_to "Sign up", new_account_path, class: 'btn btn-primary btn-lg'%></p>
  </div>
</div>